version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pezu1111
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pezu1111
      - POSTGRES_HOST=db
      - PORT=8080
      - HISTORY_SERVICE_HOST=http://192.168.56.101
      - HISTORY_SERVICE_PORT=8081
