version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pezu1111
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pezu1111
      - POSTGRES_HOST=db
      - PORT=8081
